In [280]:
import pandas as pd
import numpy as np

## Preparing Data

#### Data Gerakan Benar

Mengambil data gerakan salah dan kelas dengan nilai 1 (True)

In [281]:
data_gerakan_benar = pd.read_csv("../data/gerakan-benar.csv")
data_gerakan_benar["kelas"] = 1
data_gerakan_benar

ax1   ay1   az1   gx1   gy1   gz1   ax2   ay2   az2   gx2   gy2   gz2  \
0   2.91  6.17  3.59 -1.67 -0.46  0.92  5.53  8.00 -1.73  0.31  0.16 -0.41   
1   2.58  8.36  2.91  0.18  0.07 -0.21  5.77  7.74 -1.23 -0.14 -0.04 -0.07   
2   4.09  6.41  4.38 -1.30 -0.25  0.87  5.13  8.39 -1.98  0.41  0.09 -0.29   
3   3.58  7.54  3.47  0.51  0.13 -0.46  5.27  8.04 -1.34 -0.23 -0.09  0.00   
4   4.02  6.64  4.09 -1.16 -0.05  0.92  5.04  8.26 -1.68  0.27  0.12 -0.38   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
68  2.23  7.04  4.24 -1.14 -0.53  0.22  5.80  7.47 -2.65  0.02 -0.15 -0.33   
69  2.35  7.69  3.26 -0.87 -0.33  0.28  6.08  7.33 -2.43  0.02  0.03 -0.32   
70  3.09  8.25  2.95  0.25 -0.06 -0.08  6.68  7.25 -2.25 -0.13 -0.03 -0.02   
71  2.63  8.17  3.59 -0.46 -0.13  0.14  6.49  7.34 -2.60 -0.03 -0.04 -0.14   
72  1.72  8.17  2.93  0.57  0.00 -0.20  7.20  6.72 -2.61 -0.20 -0.13  0.02   

     ax3   ay3   az3   gx3   gy3   gz3  kelas  
0  -0.22  9.47 -2.62 -0.06  0.02  0.01      1  
1  -0.28  9.57 -2.27  0.00  0.12  0.03      1  
2  -0.09  9.46 -2.35 -0.03  0.03  0.02      1  
3  -0.18  9.62 -1.83  0.04  0.12 -0.02      1  
4   0.18  9.50 -1.97 -0.02 -0.06  0.03      1  
..   ...   ...   ...   ...   ...   ...    ...  
68  0.14  9.63 -0.03  0.04 -0.14  0.00      1  
69  0.38  9.56 -0.03  0.00  0.02  0.02      1  
70  0.25  9.66 -0.33  0.04  0.04 -0.01      1  
71  0.66  9.48  0.37 -0.02 -0.02 -0.02      1  
72  0.11  9.59  0.44 -0.02  0.01 -0.03      1  

[73 rows x 19 columns]

#### Data Gerakan Salah

Mengambil data gerakan salah dan kelas dengan nilai 0 (False)

In [282]:
data_gerakan_salah = pd.read_csv("../data/gerakan-salah.csv")
data_gerakan_salah["kelas"] = 0
data_gerakan_salah

ax1    ay1   az1   gx1   gy1   gz1   ax2   ay2   az2   gx2   gy2   gz2  \
0    3.30  -6.13  5.30 -0.14 -0.10  0.07 -0.65  5.40  1.94  0.01  0.16  0.00   
1    5.87  -2.27  6.23 -2.15  0.25  1.27  0.07  7.81  4.61  0.66  0.90 -0.36   
2    3.25   0.26  4.64  0.41 -0.50 -0.15  0.22  7.40  5.04 -0.30 -0.11 -0.08   
3    4.26  -5.44  6.57  2.04 -0.11 -0.96 -1.51  7.90  5.08 -0.18 -0.31  0.40   
4    3.66 -10.31  4.25  0.03 -0.27 -0.14 -1.82  7.20  4.15  0.12 -0.06  0.46   
..    ...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
95  10.55  -9.14  4.45  0.50  0.29 -0.54  4.86  8.96 -1.65  0.14  0.57  0.36   
96   7.16   2.13 -1.98 -1.96  0.18  0.76  8.26  4.04  1.00 -0.67 -1.24 -1.15   
97   9.42  -7.75  4.43  2.59  0.16 -2.19  7.10  8.49 -1.47  0.36  1.01  1.64   
98   6.94   0.43  0.97 -2.89  0.30  1.45  7.56  6.11 -1.07 -0.82 -1.51 -1.38   
99   6.93  -3.27  4.62  3.18 -0.19 -1.36  6.52  7.51 -1.49  0.59  1.33  1.25   

     ax3   ay3   az3   gx3   gy3   gz3  kelas  
0  -0.02  9.65 -1.23  0.03  0.08  0.03      0  
1  -0.73  9.64 -1.35  0.12  0.16  0.09      0  
2   0.23  9.55 -1.55  0.14 -0.05  0.03      0  
3   0.03  9.57 -2.13 -0.14 -0.14  0.08      0  
4   0.46  9.48 -2.38  0.09  0.09 -0.08      0  
..   ...   ...   ...   ...   ...   ...    ...  
95  1.32  9.75 -0.65 -0.01  0.00  0.01      0  
96 -0.28  9.39  0.39  0.12  0.05  0.12      0  
97  0.60  9.52 -0.28 -0.07 -0.05 -0.01      0  
98  0.17  9.62  0.46  0.07  0.02  0.31      0  
99  0.87  9.56  0.27 -0.04 -0.01 -0.09      0  

[100 rows x 19 columns]

### Menggabungkan Data

Menggabungkan data gerakan benar dan gerakan salah ke dalam satu DataFrame

In [283]:
data = pd.concat([data_gerakan_benar, data_gerakan_salah], ignore_index=True)
data

ax1   ay1   az1   gx1   gy1   gz1   ax2   ay2   az2   gx2   gy2   gz2  \
0     2.91  6.17  3.59 -1.67 -0.46  0.92  5.53  8.00 -1.73  0.31  0.16 -0.41   
1     2.58  8.36  2.91  0.18  0.07 -0.21  5.77  7.74 -1.23 -0.14 -0.04 -0.07   
2     4.09  6.41  4.38 -1.30 -0.25  0.87  5.13  8.39 -1.98  0.41  0.09 -0.29   
3     3.58  7.54  3.47  0.51  0.13 -0.46  5.27  8.04 -1.34 -0.23 -0.09  0.00   
4     4.02  6.64  4.09 -1.16 -0.05  0.92  5.04  8.26 -1.68  0.27  0.12 -0.38   
..     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
168  10.55 -9.14  4.45  0.50  0.29 -0.54  4.86  8.96 -1.65  0.14  0.57  0.36   
169   7.16  2.13 -1.98 -1.96  0.18  0.76  8.26  4.04  1.00 -0.67 -1.24 -1.15   
170   9.42 -7.75  4.43  2.59  0.16 -2.19  7.10  8.49 -1.47  0.36  1.01  1.64   
171   6.94  0.43  0.97 -2.89  0.30  1.45  7.56  6.11 -1.07 -0.82 -1.51 -1.38   
172   6.93 -3.27  4.62  3.18 -0.19 -1.36  6.52  7.51 -1.49  0.59  1.33  1.25   

      ax3   ay3   az3   gx3   gy3   gz3  kelas  
0   -0.22  9.47 -2.62 -0.06  0.02  0.01      1  
1   -0.28  9.57 -2.27  0.00  0.12  0.03      1  
2   -0.09  9.46 -2.35 -0.03  0.03  0.02      1  
3   -0.18  9.62 -1.83  0.04  0.12 -0.02      1  
4    0.18  9.50 -1.97 -0.02 -0.06  0.03      1  
..    ...   ...   ...   ...   ...   ...    ...  
168  1.32  9.75 -0.65 -0.01  0.00  0.01      0  
169 -0.28  9.39  0.39  0.12  0.05  0.12      0  
170  0.60  9.52 -0.28 -0.07 -0.05 -0.01      0  
171  0.17  9.62  0.46  0.07  0.02  0.31      0  
172  0.87  9.56  0.27 -0.04 -0.01 -0.09      0  

[173 rows x 19 columns]

## PCA

### Mengambil Fitur

Mengambil data X di mana hanya fiturnya saja tanpa kelas dari semua data yang ada

In [284]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ax1     173 non-null    float64
 1   ay1     173 non-null    float64
 2   az1     173 non-null    float64
 3   gx1     173 non-null    float64
 4   gy1     173 non-null    float64
 5   gz1     173 non-null    float64
 6   ax2     173 non-null    float64
 7   ay2     173 non-null    float64
 8   az2     173 non-null    float64
 9   gx2     173 non-null    float64
 10  gy2     173 non-null    float64
 11  gz2     173 non-null    float64
 12  ax3     173 non-null    float64
 13  ay3     173 non-null    float64
 14  az3     173 non-null    float64
 15  gx3     173 non-null    float64
 16  gy3     173 non-null    float64
 17  gz3     173 non-null    float64
dtypes: float64(18)
memory usage: 24.5 KB


### Dimensi Data

Mengambil dimensi data:

- N = Jumlah Data
- K = Dimensi Data


In [285]:
N, K = X.shape
N, K

(173, 18)

### Mean Global

Menghitung mean global dari setiap fitur dengan persamaan:

![Mean Global](../image/mean_global.png)

In [286]:
mean_global = X.mean()
mean_global

ax1    4.280809
ay1    1.909711
az1    2.353873
gx1   -0.193353
gy1   -0.051792
gz1    0.016590
ax2    4.784104
ay2    6.398555
az2   -0.243584
gx2   -0.020867
gy2   -0.004220
gz2   -0.056069
ax3    0.173757
ay3    9.345954
az3   -0.863988
gx3   -0.011098
gy3    0.056532
gz3    0.003410
dtype: float64

### Menghitung Zero Mean

Menghitung zero mean dari setiap fitur dengan persamaan:

![Zero Mean](../image/zero_mean.png)

In [287]:
X_zero_mean = pd.DataFrame()
X_zero_mean

Empty DataFrame
Columns: []
Index: []

In [288]:
for column in X.columns:
    X_zero_mean[column] = X[column] - mean_global[column]

X_zero_mean

ax1        ay1       az1       gx1       gy1      gz1       ax2  \
0   -1.370809   4.260289  1.236127 -1.476647 -0.408208  0.90341  0.745896   
1   -1.700809   6.450289  0.556127  0.373353  0.121792 -0.22659  0.985896   
2   -0.190809   4.500289  2.026127 -1.106647 -0.198208  0.85341  0.345896   
3   -0.700809   5.630289  1.116127  0.703353  0.181792 -0.47659  0.485896   
4   -0.260809   4.730289  1.736127 -0.966647  0.001792  0.90341  0.255896   
..        ...        ...       ...       ...       ...      ...       ...   
168  6.269191 -11.049711  2.096127  0.693353  0.341792 -0.55659  0.075896   
169  2.879191   0.220289 -4.333873 -1.766647  0.231792  0.74341  3.475896   
170  5.139191  -9.659711  2.076127  2.783353  0.211792 -2.20659  2.315896   
171  2.659191  -1.479711 -1.383873 -2.696647  0.351792  1.43341  2.775896   
172  2.649191  -5.179711  2.266127  3.373353 -0.138208 -1.37659  1.735896   

          ay2       az2       gx2      gy2       gz2       ax3       ay3  \
0    1.601445 -1.486416  0.330867  0.16422 -0.353931 -0.393757  0.124046   
1    1.341445 -0.986416 -0.119133 -0.03578 -0.013931 -0.453757  0.224046   
2    1.991445 -1.736416  0.430867  0.09422 -0.233931 -0.263757  0.114046   
3    1.641445 -1.096416 -0.209133 -0.08578  0.056069 -0.353757  0.274046   
4    1.861445 -1.436416  0.290867  0.12422 -0.323931  0.006243  0.154046   
..        ...       ...       ...      ...       ...       ...       ...   
168  2.561445 -1.406416  0.160867  0.57422  0.416069  1.146243  0.404046   
169 -2.358555  1.243584 -0.649133 -1.23578 -1.093931 -0.453757  0.044046   
170  2.091445 -1.226416  0.380867  1.01422  1.696069  0.426243  0.174046   
171 -0.288555 -0.826416 -0.799133 -1.50578 -1.323931 -0.003757  0.274046   
172  1.111445 -1.246416  0.610867  1.33422  1.306069  0.696243  0.214046   

          az3       gx3       gy3      gz3  
0   -1.756012 -0.048902 -0.036532  0.00659  
1   -1.406012  0.011098  0.063468  0.02659  
2   -1.486012 -0.018902 -0.026532  0.01659  
3   -0.966012  0.051098  0.063468 -0.02341  
4   -1.106012 -0.008902 -0.116532  0.02659  
..        ...       ...       ...      ...  
168  0.213988  0.001098 -0.056532  0.00659  
169  1.253988  0.131098 -0.006532  0.11659  
170  0.583988 -0.058902 -0.106532 -0.01341  
171  1.323988  0.081098 -0.036532  0.30659  
172  1.133988 -0.028902 -0.066532 -0.09341  

[173 rows x 18 columns]

### Menghitung Kovarian

Menghitung kovarian dari data dengan persamaan:

![]()

In [289]:
cov = 1 / (N - 1) * np.dot(X_zero_mean.T, X_zero_mean)
cov

array([[ 7.14500516e+00, -6.12422651e+00,  3.70850266e+00,
         2.44424822e-01,  1.77921807e-01, -1.80719899e-01,
        -5.73014968e-01,  5.41421687e+00, -3.86357548e-01,
         7.31100081e-02,  8.90261090e-02,  7.89450565e-02,
         2.64914965e-01,  1.39101549e-01,  2.43479511e+00,
        -5.15525944e-02, -3.52465956e-02, -4.49870614e-03],
       [-6.12422651e+00,  3.92919435e+01, -5.24743957e+00,
        -1.08100446e+00, -2.44279009e-01,  9.62296683e-01,
         1.53031657e+01, -5.88836612e+00, -2.06297895e+00,
        -3.59078102e-02, -3.99979134e-01, -7.97131416e-01,
        -2.95149368e+00,  1.69717382e+00,  3.30439186e+00,
         1.38534564e-01, -4.05789152e-02,  2.91800612e-02],
       [ 3.70850266e+00, -5.24743957e+00,  1.08925681e+01,
         5.57787572e-02,  9.81325615e-02, -1.59618692e-01,
        -4.73470436e+00,  7.76264865e+00, -2.10851737e-01,
         2.02674889e-01,  1.83237367e-01,  1.09396317e-01,
         6.19555132e-01, -4.19644710e-02, -4.87890278e

### Menghitung Eigenvalue dan Eigenvector

In [290]:
from numpy import linalg as LA

eigvalues, eigvectors = LA.eigh(cov)
eigvalues, eigvectors

(array([4.88612144e-03, 1.53713068e-02, 2.23765349e-02, 3.06141105e-02,
        7.08609045e-02, 1.02017915e-01, 1.33003867e-01, 1.67283485e-01,
        4.32275196e-01, 7.91508828e-01, 1.06681891e+00, 2.13779154e+00,
        3.09913343e+00, 4.30963082e+00, 6.33191129e+00, 1.07854749e+01,
        2.04445443e+01, 5.22829294e+01]),
 array([[ 6.54133093e-04, -1.40617437e-02, -6.30730992e-03,
         -1.14737597e-03, -2.09606266e-02,  3.39880172e-02,
          3.27234749e-04, -4.64516059e-02, -2.68562173e-02,
         -1.71500026e-01,  4.41579370e-01, -5.78098070e-01,
          1.77622000e-01,  2.06406292e-02,  1.35699926e-02,
          5.58688056e-01,  2.56787533e-01, -1.62644332e-01],
        [ 2.97635901e-03, -5.08822116e-03,  7.49214194e-03,
         -1.75512976e-04,  8.37546970e-03,  3.92060385e-02,
          7.37503142e-03, -2.07963329e-02, -6.69516351e-02,
         -1.72866597e-01,  1.47029151e-01, -8.27809667e-02,
          1.56324007e-01,  3.28408502e-02,  8.30805306e-02,
         

In [291]:
df_eigvalues = pd.DataFrame(data=eigvalues, index=X.columns)
df_eigvalues

0
ax1   0.004886
ay1   0.015371
az1   0.022377
gx1   0.030614
gy1   0.070861
gz1   0.102018
ax2   0.133004
ay2   0.167283
az2   0.432275
gx2   0.791509
gy2   1.066819
gz2   2.137792
ax3   3.099133
ay3   4.309631
az3   6.331911
gx3  10.785475
gy3  20.444544
gz3  52.282929

In [292]:
df_eigvalues.sort_values(by=0, ascending=False, inplace=True)
df_eigvalues

0
gz3  52.282929
gy3  20.444544
gx3  10.785475
az3   6.331911
ay3   4.309631
ax3   3.099133
gz2   2.137792
gy2   1.066819
gx2   0.791509
az2   0.432275
ay2   0.167283
ax2   0.133004
gz1   0.102018
gy1   0.070861
gx1   0.030614
az1   0.022377
ay1   0.015371
ax1   0.004886

In [293]:
df_eigvectors = pd.DataFrame(data=eigvectors, index=X.columns)
df_eigvectors

0         1         2         3         4         5         6   \
ax1  0.000654 -0.014062 -0.006307 -0.001147 -0.020961  0.033988  0.000327   
ay1  0.002976 -0.005088  0.007492 -0.000176  0.008375  0.039206  0.007375   
az1  0.000567 -0.004930 -0.002827  0.006119 -0.005325 -0.025793  0.025228   
gx1 -0.041581 -0.005160 -0.043929 -0.144022  0.180054 -0.398732 -0.099212   
gy1 -0.044014  0.141630 -0.004746  0.137778  0.844094  0.239518  0.315635   
gz1 -0.026975 -0.050825  0.163277  0.012934  0.363787 -0.670003 -0.450933   
ax2 -0.003624  0.021085 -0.015747  0.006001 -0.027135 -0.063826 -0.024060   
ay2 -0.000651  0.017298  0.011370  0.005479 -0.003525 -0.027883 -0.028065   
az2 -0.000247  0.015230  0.000298  0.000524 -0.016412 -0.002189  0.007609   
gx2 -0.192954 -0.054825 -0.058788 -0.790357  0.114715  0.346040 -0.401500   
gy2  0.095017  0.118867 -0.214742  0.516136 -0.027937  0.302460 -0.682338   
gz2  0.121417 -0.103591  0.707198  0.076134  0.179420  0.324081 -0.215228   
ax3 -0.002188 -0.025338 -0.029806 -0.030520  0.001694  0.019370  0.041866   
ay3  0.006699 -0.045549 -0.031095  0.000232  0.016802 -0.002660  0.009054   
az3  0.008916 -0.020852  0.030543 -0.003848  0.023567  0.024698  0.031615   
gx3 -0.201309 -0.223186  0.593947  0.070451 -0.239166 -0.055411  0.090288   
gy3  0.177917 -0.937648 -0.238327  0.077891  0.129550  0.059714  0.012426   
gz3  0.928586  0.126860  0.094054 -0.226204 -0.015260 -0.051414  0.028723   

           7         8         9         10        11        12        13  \
ax1 -0.046452 -0.026856 -0.171500  0.441579 -0.578098  0.177622  0.020641   
ay1 -0.020796 -0.066952 -0.172867  0.147029 -0.082781  0.156324  0.032841   
az1  0.002216 -0.058927  0.018271 -0.069311  0.055392 -0.362213 -0.285832   
gx1  0.185106 -0.001420 -0.109676  0.077715  0.191655  0.446328 -0.693337   
gy1  0.286909  0.027740  0.023058 -0.002068 -0.047293 -0.035972  0.046356   
gz1 -0.090533 -0.047591 -0.005227  0.008010 -0.105941 -0.198682  0.348911   
ax2  0.073836 -0.008211  0.592339 -0.326888 -0.123264 -0.198354 -0.214259   
ay2  0.040006  0.100545  0.275343 -0.246844  0.114627  0.284148  0.167854   
az2  0.046485 -0.214144  0.311453 -0.116909 -0.024906  0.640764  0.324211   
gx2  0.167293  0.022289  0.009359 -0.013077 -0.014005 -0.056232  0.067746   
gy2  0.310526 -0.026218 -0.043270  0.026914  0.041666  0.022642 -0.064837   
gz2 -0.461122 -0.036559  0.072038 -0.013430  0.048986  0.113041 -0.223124   
ax3  0.043376 -0.940334  0.106113  0.118508  0.002553 -0.121553 -0.066362   
ay3 -0.020755  0.121234  0.408109  0.716976  0.516454 -0.073964  0.113263   
az3 -0.023053 -0.171775 -0.466189 -0.234272  0.551396  0.029681  0.223564   
gx3  0.685360  0.023806 -0.038607  0.055177 -0.021814 -0.055278  0.071219   
gy3  0.000303  0.024649  0.012393 -0.059831 -0.028707  0.021024 -0.010617   
gz3  0.231961  0.011211 -0.012728  0.018461 -0.018328 -0.033132  0.044948   

           14        15        16        17  
ax1  0.013570  0.558688  0.256788 -0.162644  
ay1  0.083081 -0.262793  0.404850  0.818290  
az1  0.714310 -0.051311  0.461889 -0.218645  
gx1 -0.047909  0.042121 -0.030266 -0.018584  
gy1  0.004429  0.011652  0.004410 -0.005705  
gz1  0.036335 -0.022046  0.010739  0.019147  
ax2 -0.058985  0.515985 -0.011671  0.400409  
ay2 -0.371157 -0.086481  0.710691 -0.277733  
az2  0.535888  0.007822 -0.191313 -0.024426  
gx2  0.027481  0.003934  0.008486 -0.002122  
gy2  0.012699  0.009036 -0.002304 -0.008571  
gz2 -0.011585  0.011686 -0.016379 -0.014700  
ax3 -0.216719 -0.098385  0.041814 -0.080055  
ay3  0.029864  0.107879  0.040726  0.039926  
az3  0.041157  0.564189  0.100921  0.095035  
gx3  0.003206 -0.007568 -0.001666  0.003070  
gy3 -0.000414 -0.008059 -0.002302 -0.001086  
gz3  0.003639 -0.003926  0.000863  0.000283

### Transformasi

Dengan memilih nilai K dengan 75% informasi data yang kita gunakan, maka:

In [294]:
K_min_percentage = 0.75
K_percentage_temp = 0.0
sum_eigvalues = eigvalues.sum()

fitur = []

for index, value in df_eigvalues.itertuples():        
    K_percentage_temp += value / sum_eigvalues
    fitur.append(index)
    
    if K_percentage_temp > K_min_percentage:
        break
        
K_percentage_temp, fitur

(0.8169248639198257, ['gz3', 'gy3', 'gx3'])

In [295]:
df_eigvectors_selected = df_eigvectors.loc[fitur, :]
df_eigvectors_selected

0         1         2         3         4         5         6   \
gz3  0.928586  0.126860  0.094054 -0.226204 -0.015260 -0.051414  0.028723   
gy3  0.177917 -0.937648 -0.238327  0.077891  0.129550  0.059714  0.012426   
gx3 -0.201309 -0.223186  0.593947  0.070451 -0.239166 -0.055411  0.090288   

           7         8         9         10        11        12        13  \
gz3  0.231961  0.011211 -0.012728  0.018461 -0.018328 -0.033132  0.044948   
gy3  0.000303  0.024649  0.012393 -0.059831 -0.028707  0.021024 -0.010617   
gx3  0.685360  0.023806 -0.038607  0.055177 -0.021814 -0.055278  0.071219   

           14        15        16        17  
gz3  0.003639 -0.003926  0.000863  0.000283  
gy3 -0.000414 -0.008059 -0.002302 -0.001086  
gx3  0.003206 -0.007568 -0.001666  0.003070

In [296]:
principal_components = np.dot(df_eigvectors_selected.values, X_zero_mean.T).T
principal_components

array([[ 7.15483387e-02, -4.67794649e+00,  1.16180530e+00],
       [-4.33879814e-01, -6.47410801e+00,  2.67067809e-01],
       [ 1.25522841e+00, -4.83485946e+00,  1.52616464e+00],
       [ 4.33939746e-01, -5.65008009e+00,  7.60156218e-01],
       [ 1.12356753e+00, -4.94355639e+00,  1.18412787e+00],
       [-7.56009686e-01, -6.83849348e+00,  7.11394012e-01],
       [ 1.56565657e-02, -6.15891638e+00,  6.59322701e-01],
       [-4.55933843e-01, -6.20097569e+00,  3.09994079e-01],
       [ 1.10139158e+00, -4.75017532e+00,  9.55351769e-01],
       [ 2.56692289e-01, -5.78238929e+00,  5.31034355e-01],
       [-1.71417632e-01, -6.24721503e+00,  5.91880685e-01],
       [-6.97877760e-02, -4.33636744e+00,  9.46652084e-01],
       [ 1.82292168e+00, -4.81166712e+00,  2.10090454e+00],
       [ 7.53029155e-01, -4.70636108e+00,  5.99633252e-01],
       [ 7.06812963e-01, -5.66479176e+00,  9.75182696e-01],
       [ 9.50063601e-01, -3.65417800e+00,  1.19698276e+00],
       [ 2.69621326e+00, -4.78652359e+00

In [305]:
X_principal_component = pd.DataFrame(data=principal_components, columns=fitur)
X_principal_component

gz3        gy3       gx3
0    0.071548  -4.677946  1.161805
1   -0.433880  -6.474108  0.267068
2    1.255228  -4.834859  1.526165
3    0.433940  -5.650080  0.760156
4    1.123568  -4.943556  1.184128
..        ...        ...       ...
168  5.045836  10.984199  4.158520
169  2.245041   1.434129 -4.684626
170  3.739288   9.491570  4.231009
171  2.709507   2.239292 -1.346363
172  1.603189   4.844468  3.206462

[173 rows x 3 columns]

### Model Random Forest

In [306]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [307]:
X_train, X_test, y_train, y_test = train_test_split(X_principal_component, y, test_size=0.2, random_state=42)

In [308]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

rf_model

RandomForestClassifier(random_state=42)

In [309]:
pred = rf_model.predict(X_test)
pred

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0])

In [310]:
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test, pred)

print(f'Score dengan jumlah principal component {len(fitur)}\t: {score}')

Score dengan jumlah principal component 3	: 0.9428571428571428


In [311]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf_model, X_principal_component, y, cv=5)
scores.mean()

0.8677310924369749