In [581]:
import pandas as pd
import numpy as np

## Data Preparation

In [582]:
data_gerakan_benar = pd.read_csv('../data/gerakan-benar.csv')
data_gerakan_benar["kelas"] = 1
data_gerakan_benar.head()

ax1   ay1   az1   gx1   gy1   gz1   ax2   ay2   az2   gx2   gy2   gz2  \
0  2.91  6.17  3.59 -1.67 -0.46  0.92  5.53  8.00 -1.73  0.31  0.16 -0.41   
1  2.58  8.36  2.91  0.18  0.07 -0.21  5.77  7.74 -1.23 -0.14 -0.04 -0.07   
2  4.09  6.41  4.38 -1.30 -0.25  0.87  5.13  8.39 -1.98  0.41  0.09 -0.29   
3  3.58  7.54  3.47  0.51  0.13 -0.46  5.27  8.04 -1.34 -0.23 -0.09  0.00   
4  4.02  6.64  4.09 -1.16 -0.05  0.92  5.04  8.26 -1.68  0.27  0.12 -0.38   

    ax3   ay3   az3   gx3   gy3   gz3  kelas  
0 -0.22  9.47 -2.62 -0.06  0.02  0.01      1  
1 -0.28  9.57 -2.27  0.00  0.12  0.03      1  
2 -0.09  9.46 -2.35 -0.03  0.03  0.02      1  
3 -0.18  9.62 -1.83  0.04  0.12 -0.02      1  
4  0.18  9.50 -1.97 -0.02 -0.06  0.03      1

In [583]:
data_gerakan_salah = pd.read_csv('../data/gerakan-salah.csv')
data_gerakan_salah["kelas"] = 0
data_gerakan_salah.head()

ax1    ay1   az1   gx1   gy1   gz1   ax2   ay2   az2   gx2   gy2   gz2  \
0  3.30  -6.13  5.30 -0.14 -0.10  0.07 -0.65  5.40  1.94  0.01  0.16  0.00   
1  5.87  -2.27  6.23 -2.15  0.25  1.27  0.07  7.81  4.61  0.66  0.90 -0.36   
2  3.25   0.26  4.64  0.41 -0.50 -0.15  0.22  7.40  5.04 -0.30 -0.11 -0.08   
3  4.26  -5.44  6.57  2.04 -0.11 -0.96 -1.51  7.90  5.08 -0.18 -0.31  0.40   
4  3.66 -10.31  4.25  0.03 -0.27 -0.14 -1.82  7.20  4.15  0.12 -0.06  0.46   

    ax3   ay3   az3   gx3   gy3   gz3  kelas  
0 -0.02  9.65 -1.23  0.03  0.08  0.03      0  
1 -0.73  9.64 -1.35  0.12  0.16  0.09      0  
2  0.23  9.55 -1.55  0.14 -0.05  0.03      0  
3  0.03  9.57 -2.13 -0.14 -0.14  0.08      0  
4  0.46  9.48 -2.38  0.09  0.09 -0.08      0

In [584]:
data = pd.concat([data_gerakan_benar, data_gerakan_salah], ignore_index=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ax1     173 non-null    float64
 1   ay1     173 non-null    float64
 2   az1     173 non-null    float64
 3   gx1     173 non-null    float64
 4   gy1     173 non-null    float64
 5   gz1     173 non-null    float64
 6   ax2     173 non-null    float64
 7   ay2     173 non-null    float64
 8   az2     173 non-null    float64
 9   gx2     173 non-null    float64
 10  gy2     173 non-null    float64
 11  gz2     173 non-null    float64
 12  ax3     173 non-null    float64
 13  ay3     173 non-null    float64
 14  az3     173 non-null    float64
 15  gx3     173 non-null    float64
 16  gy3     173 non-null    float64
 17  gz3     173 non-null    float64
 18  kelas   173 non-null    int64  
dtypes: float64(18), int64(1)
memory usage: 25.8 KB


In [585]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

n_samples, n_features = X.shape

print('Number of samples:', n_samples)
print('Number of features:', n_features)

Number of samples: 173
Number of features: 18


## PCA dengan metode Kovarian

### Mencari Matriks Kovarian

In [586]:
def covariance(x):
    return (x.T @ x)/(x.shape[0] - 1)

cov_mat = covariance(X)
cov_mat

ax1        ay1        az1       gx1       gy1       gz1        ax2  \
ax1  25.576876   2.098412  13.843567 -0.588093 -0.045078 -0.109290  20.025891   
ay1   2.098412  42.960143  -0.726088 -1.452399 -0.343762  0.994162  24.492540   
az1  13.843567  -0.726088  16.465499 -0.401995 -0.024488 -0.120342   6.591940   
gx1  -0.588093  -1.452399  -0.401995  2.917876 -0.187860 -1.374315  -0.818265   
gy1  -0.045078  -0.343762  -0.024488 -0.187860  0.109457  0.076567  -0.303879   
gz1  -0.109290   0.994162  -0.120342 -1.374315  0.076567  0.791687   0.168549   
ax2  20.025891  24.492540   6.591940 -0.818265 -0.303879  0.168549  35.044909   
ay2  32.964460   6.402067  22.911599 -1.444285 -0.210730 -0.030970  24.318598   
az2  -1.435156  -2.530858  -0.787551 -0.097541  0.019516  0.150191  -2.292980   
gx2  -0.016737  -0.075990   0.153271 -0.292085  0.028522  0.144225  -0.149910   
gy2   0.070858  -0.408084   0.173247  0.262821 -0.022376 -0.114165  -0.143939   
gz2  -0.162473  -0.904830  -0.023351  0.856553 -0.066773 -0.435512  -0.349773   
ax3   1.013061  -2.617738   1.030935  0.071751 -0.005177 -0.104677  -1.169010   
ay3  40.379953  19.649012  22.085124 -2.047226 -0.494495  0.287215  46.132662   
az3  -1.285278   1.644831  -2.533433 -0.124679  0.075538  0.172163   0.425565   
gx3  -0.099338   0.117217  -0.091128 -0.276101  0.041523  0.135495  -0.086791   
gy3   0.208162   0.068008   0.117100  0.029940  0.003257 -0.023929   0.235285   
gz3   0.010185   0.035731   0.009715 -0.179970  0.023094  0.092337  -0.026750   

           ay2       az2       gx2       gy2       gz2       ax3        ay3  \
ax1  32.964460 -1.435156 -0.016737  0.070858 -0.162473  1.013061  40.379953   
ay1   6.402067 -2.530858 -0.075990 -0.408084 -0.904830 -2.617738  19.649012   
az1  22.911599 -0.787551  0.153271  0.173247 -0.023351  1.030935  22.085124   
gx1  -1.444285 -0.097541 -0.292085  0.262821  0.856553  0.071751  -2.047226   
gy1  -0.210730  0.019516  0.028522 -0.022376 -0.066773 -0.005177  -0.494495   
gz1  -0.030970  0.150191  0.144225 -0.114165 -0.435512 -0.104677   0.287215   
ax2  24.318598 -2.292980 -0.149910 -0.143939 -0.349773 -1.169010  46.132662   
ay2  57.021091 -4.377046 -0.044489 -0.005020 -0.404347  3.286025  60.038023   
az2  -4.377046  4.496526  0.054479  0.007122 -0.012923 -1.082998  -2.405946   
gx2  -0.044489  0.054479  0.096259  0.021344 -0.078806 -0.037116  -0.160016   
gy2  -0.005020  0.007122  0.021344  0.128730  0.082903  0.025481  -0.034104   
gz2  -0.404347 -0.012923 -0.078806  0.082903  0.352760  0.077544  -0.628588   
ax3   3.286025 -1.082998 -0.037116  0.025481  0.077544  1.274523   1.419482   
ay3  60.038023 -2.405946 -0.160016 -0.034104 -0.628588  1.419482  89.432288   
az3  -5.821750  0.154792  0.096745  0.010945 -0.154855 -1.188656  -6.802645   
gx3  -0.160523 -0.006484  0.038444 -0.000886 -0.146391 -0.013223  -0.055979   
gy3   0.377422  0.030767 -0.005062  0.000219  0.014426  0.000651   0.436591   
gz3   0.018810  0.000837  0.027101 -0.011427 -0.078675 -0.002614   0.048484   

          az3       gx3       gy3       gz3  
ax1 -1.285278 -0.099338  0.208162  0.010185  
ay1  1.644831  0.117217  0.068008  0.035731  
az1 -2.533433 -0.091128  0.117100  0.009715  
gx1 -0.124679 -0.276101  0.029940 -0.179970  
gy1  0.075538  0.041523  0.003257  0.023094  
gz1  0.172163  0.135495 -0.023929  0.092337  
ax2  0.425565 -0.086791  0.235285 -0.026750  
ay2 -5.821750 -0.160523  0.377422  0.018810  
az2  0.154792 -0.006484  0.030767  0.000837  
gx2  0.096745  0.038444 -0.005062  0.027101  
gy2  0.010945 -0.000886  0.000219 -0.011427  
gz2 -0.154855 -0.146391  0.014426 -0.078675  
ax3 -1.188656 -0.013223  0.000651 -0.002614  
ay3 -6.802645 -0.055979  0.436591  0.048484  
az3  5.986862  0.010406 -0.141455 -0.005652  
gx3  0.010406  0.131412 -0.011553  0.049192  
gy3 -0.141455 -0.011553  0.028606 -0.006262  
gz3 -0.005652  0.049192 -0.006262  0.029276

### Mencari Eigenvector dan Eigenvalue dari Matriks Kovarian

In [587]:
from numpy.linalg import eig

eig_vals, eig_vecs = eig(cov_mat)

In [588]:
eig_vals

array([1.89813934e+02, 5.21004129e+01, 1.47492439e+01, 8.45301666e+00,
       6.28476539e+00, 4.30052824e+00, 3.09893242e+00, 2.08618179e+00,
       9.67043402e-01, 4.40653672e-01, 1.67461267e-01, 1.33145544e-01,
       1.02869108e-01, 7.10920238e-02, 4.91591473e-03, 1.61333980e-02,
       2.37216762e-02, 3.07273334e-02])

In [589]:
eig_vecs

array([[ 3.26961860e-01,  1.90406023e-01,  1.28023757e-01,
        -5.00433087e-01,  3.35632352e-02, -3.24227531e-02,
         1.79690138e-01, -5.92060617e-01,  4.47537306e-01,
         2.65719016e-02,  4.69037594e-02,  7.19974357e-04,
        -3.41188103e-02,  2.12007057e-02,  2.41284820e-04,
        -1.23835752e-02,  7.22962722e-03, -8.10422836e-04],
       [ 1.74636107e-01, -8.02327686e-01, -4.83444459e-01,
         3.11231503e-02, -7.38314921e-02, -3.72691715e-02,
         1.57248602e-01, -7.23284806e-02,  2.23111278e-01,
         5.18157244e-02,  1.93318227e-02,  6.25797748e-03,
        -3.56609401e-02, -6.06160399e-03,  3.58068971e-03,
        -9.17951788e-03, -1.88849084e-03,  1.10277200e-03],
       [ 1.90782261e-01,  2.39141171e-01, -4.10658755e-01,
        -2.11547061e-01, -6.84309512e-01,  2.84660236e-01,
        -3.62251819e-01,  6.16870507e-02, -6.27327631e-02,
         5.72997726e-02, -2.77622639e-03,  2.44935299e-02,
         2.71719010e-02,  5.57479380e-03,  5.56520547e

In [590]:
max_abs_idx = np.argmax(np.abs(eig_vecs), axis=0)
signs = np.sign(eig_vecs[max_abs_idx, range(eig_vecs.shape[0])])
eig_vecs = eig_vecs*signs[np.newaxis,:]
eig_vecs = eig_vecs.T

In [591]:
print(signs)

[ 1. -1. -1. -1. -1.  1.  1.  1. -1.  1. -1. -1.  1. -1.  1. -1. -1. -1.]


In [592]:
np.abs(eig_vals)

array([1.89813934e+02, 5.21004129e+01, 1.47492439e+01, 8.45301666e+00,
       6.28476539e+00, 4.30052824e+00, 3.09893242e+00, 2.08618179e+00,
       9.67043402e-01, 4.40653672e-01, 1.67461267e-01, 1.33145544e-01,
       1.02869108e-01, 7.10920238e-02, 4.91591473e-03, 1.61333980e-02,
       2.37216762e-02, 3.07273334e-02])

In [593]:
np.abs(eig_vecs)

array([[3.26961860e-01, 1.74636107e-01, 1.90782261e-01, 1.55197984e-02,
        3.29294706e-03, 1.91668872e-03, 3.56370130e-01, 4.94829497e-01,
        3.06423195e-02, 9.15309763e-04, 5.10199570e-04, 5.11023968e-03,
        1.22859037e-02, 6.71637485e-01, 4.31465008e-02, 9.10332975e-04,
        3.53401471e-03, 2.48484095e-04],
       [1.90406023e-01, 8.02327686e-01, 2.39141171e-01, 1.72097508e-02,
        5.63107291e-03, 1.89422675e-02, 3.76806843e-01, 3.22488490e-01,
        1.89908637e-02, 2.23321825e-03, 8.53891073e-03, 1.41545974e-02,
        8.14873664e-02, 4.25426660e-03, 9.40720773e-02, 3.18150471e-03,
        1.21280485e-03, 2.64059687e-04],
       [1.28023757e-01, 4.83444459e-01, 4.10658755e-01, 4.01597943e-02,
        1.36456070e-03, 1.98094209e-02, 3.82918170e-01, 5.02893744e-01,
        1.84386956e-01, 7.95176503e-03, 5.82468084e-03, 2.01335011e-02,
        6.76708181e-02, 3.63942290e-01, 9.04079657e-02, 1.46409520e-03,
        1.73689604e-05, 2.25694298e-03],
       [5.004

### Rearrange the Eigenvectors and Eigenvalues

In [594]:
# We first make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[i,:]) for i in range(len(eig_vals))]

# Then, we sort the tuples from the highest to the lowest based on eigenvalues magnitude
eig_pairs.sort(key=lambda x: x[0], reverse=True)

# For further usage
eig_vals_sorted = np.array([x[0] for x in eig_pairs])
eig_vecs_sorted = np.array([x[1] for x in eig_pairs])

print(eig_pairs)

[(189.81393389902007, array([ 3.26961860e-01,  1.74636107e-01,  1.90782261e-01, -1.55197984e-02,
       -3.29294706e-03,  1.91668872e-03,  3.56370130e-01,  4.94829497e-01,
       -3.06423195e-02, -9.15309763e-04, -5.10199570e-04, -5.11023968e-03,
        1.22859037e-02,  6.71637485e-01, -4.31465008e-02, -9.10332975e-04,
        3.53401471e-03,  2.48484095e-04])), (52.100412879614645, array([-1.90406023e-01,  8.02327686e-01, -2.39141171e-01, -1.72097508e-02,
       -5.63107291e-03,  1.89422675e-02,  3.76806843e-01, -3.22488490e-01,
       -1.89908637e-02, -2.23321825e-03, -8.53891073e-03, -1.41545974e-02,
       -8.14873664e-02, -4.25426660e-03,  9.40720773e-02,  3.18150471e-03,
       -1.21280485e-03,  2.64059687e-04])), (14.749243868738946, array([-1.28023757e-01,  4.83444459e-01,  4.10658755e-01, -4.01597943e-02,
        1.36456070e-03,  1.98094209e-02, -3.82918170e-01,  5.02893744e-01,
       -1.84386956e-01,  7.95176503e-03, -5.82468084e-03, -2.01335011e-02,
        6.76708181e-02,

### Choose Principal Components

In [595]:
# Select top k eigenvectors
k = 3
W = eig_vecs_sorted[:k, :] # Projection matrix

print(W.shape)

(3, 18)


In [596]:
eig_vals_total = sum(eig_vals)
explained_variance = [(i / eig_vals_total)*100 for i in eig_vals_sorted]
explained_variance = np.round(explained_variance, 2)
cum_explained_variance = np.cumsum(explained_variance)

print('Explained variance: {}'.format(explained_variance))
print('Cumulative explained variance: {}'.format(cum_explained_variance))

Explained variance: [6.711e+01 1.842e+01 5.210e+00 2.990e+00 2.220e+00 1.520e+00 1.100e+00
 7.400e-01 3.400e-01 1.600e-01 6.000e-02 5.000e-02 4.000e-02 3.000e-02
 1.000e-02 1.000e-02 1.000e-02 0.000e+00]
Cumulative explained variance: [ 67.11  85.53  90.74  93.73  95.95  97.47  98.57  99.31  99.65  99.81
  99.87  99.92  99.96  99.99 100.   100.01 100.02 100.02]


### Project the Data

In [597]:
X_proj = X.dot(W.T)

print(X_proj.shape)

(173, 3)


In [598]:
def covariance_matrix(X):
    """
    Menghitung matriks kovarian dari data X.

    Parameters:
    - X: np.array, matriks data dengan setiap kolom mewakili suatu fitur.

    Returns:
    - cov_mat: np.array, matriks kovarian dari data X.
    """
    n_samples, n_features = X.shape

    # Menghitung rata-rata setiap fitur
    mean_vector = np.mean(X, axis=0)

    # Menghitung deviasi dari rata-rata
    deviation_matrix = X - mean_vector

    # Menghitung matriks kovarian
    cov_mat = np.dot(deviation_matrix.T, deviation_matrix) / (n_samples - 1)

    return cov_mat

In [613]:
class MyPCA:

    def __init__(self, n_components):
        self.n_components = n_components

    def fit(self, X):
        X = X.copy()

        # Eigendecomposition of covariance matrix       
        cov_mat = covariance_matrix(X)
        eig_vals, eig_vecs = np.linalg.eig(cov_mat) 
        eig_vecs = eig_vecs.T

        eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[i,:]) for i in range(len(eig_vals))]
        eig_pairs.sort(key=lambda x: x[0], reverse=True)
        eig_vals_sorted = np.array([x[0] for x in eig_pairs])
        eig_vecs_sorted = np.array([x[1] for x in eig_pairs])

        self.components = eig_vecs_sorted[:self.n_components,:]

        # Explained variance ratio
        self.explained_variance_ratio = [i/np.sum(eig_vals) for i in eig_vals_sorted[:self.n_components]]
        self.cum_explained_variance = np.cumsum(self.explained_variance_ratio)

        return self

    def transform(self, X):
        X = X.copy()
        X_proj = X.dot(self.components.T)

        return X_proj

In [615]:
my_pca = MyPCA(n_components = 3).fit(X)

print('Components:\n', my_pca.components)
print('Explained variance ratio from scratch:\n', my_pca.explained_variance_ratio)
print('Cumulative explained variance from scratch:\n', my_pca.cum_explained_variance)

X_proj = my_pca.transform(X)
print('Transformed data shape from scratch:', X_proj.shape)

Components:
 [[-1.62644332e-01  8.18289584e-01 -2.18644803e-01 -1.85844041e-02
  -5.70476916e-03  1.91467218e-02  4.00408773e-01 -2.77733336e-01
  -2.44263499e-02 -2.12168971e-03 -8.57111945e-03 -1.46995312e-02
  -8.00548080e-02  3.99262565e-02  9.50350761e-02  3.06955946e-03
  -1.08642231e-03  2.82763012e-04]
 [-2.56787533e-01 -4.04849784e-01 -4.61889033e-01  3.02664268e-02
  -4.41012934e-03 -1.07389376e-02  1.16705890e-02 -7.10690694e-01
   1.91312979e-01 -8.48603098e-03  2.30389228e-03  1.63785944e-02
  -4.18136257e-02 -4.07262492e-02 -1.00920647e-01  1.66599431e-03
   2.30225407e-03 -8.63478079e-04]
 [-5.58688056e-01  2.62792739e-01  5.13105284e-02 -4.21211584e-02
  -1.16515663e-02  2.20462567e-02 -5.15985363e-01  8.64809769e-02
  -7.82163516e-03 -3.93420931e-03 -9.03646056e-03 -1.16864967e-02
   9.83848891e-02 -1.07879038e-01 -5.64188808e-01  7.56839972e-03
   8.05925938e-03  3.92615358e-03]]
Explained variance ratio from scratch:
 [0.5114323669126934, 0.19998882663234757, 0.10550

In [616]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 3).fit(X)

print('Components:\n', pca.components_)
print('Explained variance ratio:\n', pca.explained_variance_ratio_)

cum_explained_variance = np.cumsum(pca.explained_variance_ratio_)
print('Cumulative explained variance:\n', cum_explained_variance)

X_pca = pca.transform(X) # Apply dimensionality reduction to X.
print('Transformed data shape:', X_pca.shape)

Components:
 [[ 1.62644332e-01 -8.18289584e-01  2.18644803e-01  1.85844041e-02
   5.70476916e-03 -1.91467218e-02 -4.00408773e-01  2.77733336e-01
   2.44263499e-02  2.12168971e-03  8.57111945e-03  1.46995312e-02
   8.00548080e-02 -3.99262565e-02 -9.50350761e-02 -3.06955946e-03
   1.08642231e-03 -2.82763012e-04]
 [-2.56787533e-01 -4.04849784e-01 -4.61889033e-01  3.02664268e-02
  -4.41012934e-03 -1.07389376e-02  1.16705890e-02 -7.10690694e-01
   1.91312979e-01 -8.48603098e-03  2.30389228e-03  1.63785944e-02
  -4.18136257e-02 -4.07262492e-02 -1.00920647e-01  1.66599431e-03
   2.30225407e-03 -8.63478079e-04]
 [-5.58688056e-01  2.62792739e-01  5.13105284e-02 -4.21211584e-02
  -1.16515663e-02  2.20462567e-02 -5.15985363e-01  8.64809769e-02
  -7.82163516e-03 -3.93420931e-03 -9.03646056e-03 -1.16864967e-02
   9.83848891e-02 -1.07879038e-01 -5.64188808e-01  7.56839972e-03
   8.05925938e-03  3.92615358e-03]]
Explained variance ratio:
 [0.51143237 0.19998883 0.10550367]
Cumulative explained varian

In [617]:
pd.DataFrame(pca.components_,columns=X.columns,index = ['PC-1','PC-2','PC-3'])

ax1       ay1       az1       gx1       gy1       gz1       ax2  \
PC-1  0.162644 -0.818290  0.218645  0.018584  0.005705 -0.019147 -0.400409   
PC-2 -0.256788 -0.404850 -0.461889  0.030266 -0.004410 -0.010739  0.011671   
PC-3 -0.558688  0.262793  0.051311 -0.042121 -0.011652  0.022046 -0.515985   

           ay2       az2       gx2       gy2       gz2       ax3       ay3  \
PC-1  0.277733  0.024426  0.002122  0.008571  0.014700  0.080055 -0.039926   
PC-2 -0.710691  0.191313 -0.008486  0.002304  0.016379 -0.041814 -0.040726   
PC-3  0.086481 -0.007822 -0.003934 -0.009036 -0.011686  0.098385 -0.107879   

           az3       gx3       gy3       gz3  
PC-1 -0.095035 -0.003070  0.001086 -0.000283  
PC-2 -0.100921  0.001666  0.002302 -0.000863  
PC-3 -0.564189  0.007568  0.008059  0.003926

### Apply to Model

In [618]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

### Tanpa Library

In [619]:
X_train_proj, X_test_proj, y_train_proj, y_test_proj = train_test_split(X_proj, y, test_size=0.2, random_state=42) 

In [620]:
clf_proj = RandomForestClassifier(n_estimators=100, random_state=42)
clf_proj.fit(X_train_proj, y_train_proj)

RandomForestClassifier(random_state=42)

In [621]:
pred_proj = clf_proj.predict(X_test_proj)
accuracy_proj = accuracy_score(y_test_proj, pred_proj)

print(f'Tanpa Library\nAccuracy: {accuracy_proj}')

Tanpa Library
Accuracy: 0.9714285714285714


In [622]:
cv_clf_proj = RandomForestClassifier(n_estimators=100, random_state=42)

score_cv_proj = cross_val_score(cv_clf_proj, X_proj, y, cv=5)

print(f'Tanpa Library\nCross Val Scores\t: {score_cv_proj}\nMean\t\t\t\t: {score_cv_proj.mean()}')

Tanpa Library
Cross Val Scores	: [0.97142857 0.88571429 0.71428571 0.85294118 0.97058824]
Mean				: 0.8789915966386556


### Dengan Library

In [623]:
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.2, random_state=42) 

In [624]:
clf_pca = RandomForestClassifier(n_estimators=100, random_state=42)
clf_pca.fit(X_train_pca, y_train_pca)

RandomForestClassifier(random_state=42)

In [625]:
pred_pca = clf_pca.predict(X_test_pca)
accuracy_pca = accuracy_score(y_test_pca, pred_pca)

print(f'Dengan Library\nAccuracy: {accuracy_pca}')

Dengan Library
Accuracy: 0.9714285714285714


In [626]:
cv_clf_pca = RandomForestClassifier(n_estimators=100, random_state=42)

score_cv_pca = cross_val_score(cv_clf_pca, X_pca, y, cv=5)

print(f'Dengan Library\nCross Val Scores\t: {score_cv_pca}\nMean\t\t\t\t: {score_cv_pca.mean()}')

Dengan Library
Cross Val Scores	: [0.97142857 0.88571429 0.71428571 0.85294118 0.97058824]
Mean				: 0.8789915966386556
